= JBoss EAP BOMs

The JBoss EAP BOMs project provides Maven BOM files, which includes dependency management compatible with (same version) JBoss EAP. These files manage the version of the dependencies you may need to build, test or debug your project, ensuring you always get a compatible stack.

The following BOMs are available:

* EJB Client (Maven coordinates "org.jboss.eap:wildfly-ejb-client-bom", built by ./client/ejb-client/pom.xml)
* JAXWS Client (Maven coordinates "org.jboss.eap:wildfly-jaxws-client-bom", built by ./client/jaxws-client/pom.xml)
* JMS Client (Maven coordinates "org.jboss.eap:wildfly-jms-client-bom", built by ./client/jms-client/pom.xml)
* Tools (Maven coordinates "org.jboss.bom:jboss-eap-tools", built by ./tools/pom.xml)
* EE (Maven coordinates "org.jboss.bom:jboss-eap-ee", built by ./server/ee/legacy/pom.xml)
* EE With Tools (Maven coordinates "org.jboss.bom:jboss-eap-ee-with-tools", built by ./server/ee/legacy/with-tools/pom.xml)
* EE 11 (Maven coordinates "org.jboss.bom:jboss-eap-ee-11", built by ./server/ee/standard/pom.xml)
* EE 11 With Tools (Maven coordinates "org.jboss.bom:jboss-eap-ee-11-with-tools", built by ./server/ee/standard/with-tools/pom.xml)
* Expansion (Maven coordinates "org.jboss.bom:jboss-eap-expansion", built by ./server/expansion/legacy/pom.xml)
* Expansion With Tools (Maven coordinates "org.jboss.bom:jboss-eap-expansion-with-tools", built by ./server/expansion/legacy/with-tools/pom.xml)
* Expansion EE 11 (Maven coordinates "org.jboss.bom:jboss-eap-expansion-ee-11", built by ./server/expansion/standard/pom.xml)
* Expansion EE 11 With Tools (Maven coordinates "org.jboss.bom:jboss-eap-expansion-ee-11-with-tools", built by ./server/expansion/standard/with-tools/pom.xml)
== Usage

To use a BOM, import into your dependency management. For example, if you want to import the traditional server's EE dependency management, provided by the "EE" BOM, use:

[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jboss.bom</groupId>
            <artifactId>jboss-eap-ee</artifactId>
            <version>${eap.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----